
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.DocFlavor;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.Timer;


public class BankReserve extends javax.swing.JFrame {

    public BankReserve() {
        initComponents();
        bankreserve.setEditable(false);
        displayBankReserve();
        displayDateTime();
         startTimer(); // Start the timer for continuous time update
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bankreserve = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        approvals = new javax.swing.JButton();
        banktransac = new javax.swing.JButton();
        bankreserve1 = new javax.swing.JButton();
        clients = new javax.swing.JButton();
        timeanddate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bankreserve.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bankreserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankreserveActionPerformed(evt);
            }
        });
        getContentPane().add(bankreserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 470, 40));

        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, 130, 110));

        approvals.setBorderPainted(false);
        approvals.setContentAreaFilled(false);
        approvals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approvalsActionPerformed(evt);
            }
        });
        getContentPane().add(approvals, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 170, 100));

        banktransac.setBorderPainted(false);
        banktransac.setContentAreaFilled(false);
        banktransac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banktransacActionPerformed(evt);
            }
        });
        getContentPane().add(banktransac, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 170, 100));

        bankreserve1.setBorderPainted(false);
        bankreserve1.setContentAreaFilled(false);
        bankreserve1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankreserve1ActionPerformed(evt);
            }
        });
        getContentPane().add(bankreserve1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 170, 100));

        clients.setBorderPainted(false);
        clients.setContentAreaFilled(false);
        clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsActionPerformed(evt);
            }
        });
        getContentPane().add(clients, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 220, 100));

        timeanddate.setBackground(new java.awt.Color(255, 255, 255));
        timeanddate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        timeanddate.setForeground(new java.awt.Color(0, 0, 0));
        timeanddate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(timeanddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 490, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BankReserve.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 576));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bankreserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankreserveActionPerformed
        bankreserve.setEditable(false);
        try {
            BufferedReader userTransactionsReader = new BufferedReader(new FileReader("transactions.csv"));
        String line;
            while ((line=userTransactionsReader.readLine())!=null) {
                String[] accountDetails=line.split(",");
                if (accountDetails[0].equals("BANK")){
                    bankreserve.setText(accountDetails[1]);
                    
                    
                }
                
            }
            
           userTransactionsReader.close();
        
        
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BankReserve.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BankReserve.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_bankreserveActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        new AdminLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void approvalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approvalsActionPerformed
        new Approval().setVisible(true);
        dispose();
    }//GEN-LAST:event_approvalsActionPerformed

    private void banktransacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banktransacActionPerformed
        new BankTransactions().setVisible(true);
        dispose();
    }//GEN-LAST:event_banktransacActionPerformed

    private void bankreserve1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankreserve1ActionPerformed
        new BankReserve().setVisible(true);
        dispose();
    }//GEN-LAST:event_bankreserve1ActionPerformed

    private void clientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientsActionPerformed
        new Clients().setVisible(true);
        dispose();
    }//GEN-LAST:event_clientsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankReserve().setVisible(true);
            }
        });
    }
    
    public BankReserve(JTextField bankreserve, JLabel jLabel1) throws HeadlessException {
        this.bankreserve = bankreserve;
        this.jLabel1 = jLabel1;
    }
    public void displayBankReserve(){
        try {
            BufferedReader userTransactionsReader = new BufferedReader(new FileReader("transactions.csv"));
        String line;
            while ((line=userTransactionsReader.readLine())!=null) {
                String[] accountDetails=line.split(",");
                if (accountDetails[0].equals("BANK")){
                    bankreserve.setText(accountDetails[1]);
                    
                    
                }
                
            }
            
           userTransactionsReader.close();
        
        
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BankReserve.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BankReserve.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approvals;
    private javax.swing.JTextField bankreserve;
    private javax.swing.JButton bankreserve1;
    private javax.swing.JButton banktransac;
    private javax.swing.JButton clients;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel timeanddate;
    // End of variables declaration//GEN-END:variables
  // Method to display the current date and time in the timeanddate label
    private void displayDateTime() {
        // Create a SimpleDateFormat object to format the date and time
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        // Get the current date and time
        Date currentDate = new Date();
        // Format the current date and time
        String formattedDateTime = dateFormat.format(currentDate);
        // Set the formatted date and time to the timeanddate label
        timeanddate.setText(formattedDateTime);
    }

   
     // Method to start a timer to update the displayed time every second
    private void startTimer() {
        Timer timer = new Timer(1000, (e) -> {
            displayDateTime();
        });
        timer.start();
    }}
